var mongoose = require('mongoose');

module.exports = mongoose.model('Contact', {        // Create a model called Contact and export it
	firstName: String,
	lastName: String,
	email1: String,
	email2: String,
	email3: String,
	email4: String,
	phone1: String,
	phone2: String,
	phone3: String,
	phone4: String,
	address1: String,
	address2: String,
	address3: String,
	address4: String,
	city1: String,
	city2: String,
	state1: String,
	state2: String,
	zip1: String,
	zip2: String,
	photo: String,
	notes1: String,
	notes2: String,
	created: Date,
	updated: Date,
    category: {type:mongoose.Schema.Types.ObjectId, ref:'Category'}   // category is an ObjectId that references the Category model
});
